"""Polars-native BIDS Derivatives storage for processed eye-tracking data."""

from __future__ import annotations

import json
import re
import shutil
from collections.abc import Mapping
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

import polars as pl

from pyxations.bids import BIDS_VERSION, bids_label
from pyxations.tables import (
    SessionTables,
    frame_payload,
    payload_frame,
    read_tsv,
    write_tsv,
)


def _write_json(path: Path, value: Mapping) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False)
        stream.write("\n")


def _column_label(value: str) -> str:
    label = re.sub(r"[^a-z0-9]+", "_", str(value).lower()).strip("_")
    return label or "column"


def _column_mapping(
    columns,
) -> tuple[dict[str, str], dict[str, str]]:
    """Return original-to-BIDS and BIDS-to-original column mappings."""

    original_to_bids: dict[str, str] = {}
    bids_to_original: dict[str, str] = {}
    for original_value in columns:
        original = str(original_value)
        base = f"pyx_{_column_label(original)}"
        candidate = base
        index = 2
        while candidate in bids_to_original and bids_to_original[candidate] != original:
            candidate = f"{base}_{index}"
            index += 1
        original_to_bids[original] = candidate
        bids_to_original[candidate] = original
    return original_to_bids, bids_to_original


def _unit_scale(unit: str | None) -> float:
    return {
        "s": 1.0,
        "ms": 1_000.0,
        "us": 1_000_000.0,
        "µs": 1_000_000.0,
    }.get(str(unit).lower(), 1_000.0)


def _numeric_series(frame: pl.DataFrame, column: str) -> pl.Series:
    return frame.get_column(column).cast(pl.Float64, strict=False)


def _finite_values(series: pl.Series) -> pl.Series:
    return series.filter(series.is_not_null() & series.is_finite())


def _infer_frequency(seconds: pl.Series) -> float:
    numeric = _finite_values(seconds.cast(pl.Float64, strict=False)).sort()
    if numeric.len() < 2:
        return 1.0
    differences = numeric.diff().drop_nulls()
    differences = differences.filter(differences > 0)
    if differences.is_empty():
        return 1.0
    return float(1.0 / differences.median())


def _package_version() -> str:
    try:
        return version("pyxations")
    except PackageNotFoundError:
        return "development"


def initialize_bids_derivative(
    raw_dataset: str | Path,
    derivative_dataset: str | Path,
) -> Path:
    """Create dataset-level metadata for a standalone BIDS Derivatives dataset.

    Parameters
    ----------
    raw_dataset : str or pathlib.Path
        Source raw BIDS dataset.
    derivative_dataset : str or pathlib.Path
        Destination derivative dataset.

    Returns
    -------
    pathlib.Path
        Initialized derivative dataset root.
    """

    raw_root = Path(raw_dataset)
    derivative_root = Path(derivative_dataset)
    derivative_root.mkdir(parents=True, exist_ok=True)
    _write_json(
        derivative_root / "dataset_description.json",
        {
            "Name": f"{raw_root.name} Pyxations derivatives",
            "BIDSVersion": BIDS_VERSION,
            "DatasetType": "derivative",
            "GeneratedBy": [
                {
                    "Name": "Pyxations",
                    "Version": _package_version(),
                    "Description": (
                        "Eye-movement detection, preprocessing, and trial "
                        "annotation of BIDS eye-tracking recordings."
                    ),
                }
            ],
            "SourceDatasets": [{"URL": f"../{raw_root.name}/"}],
        },
    )
    for filename in ("participants.tsv", "participants.json"):
        source = raw_root / filename
        if source.is_file():
            shutil.copy2(source, derivative_root / filename)
    (derivative_root / "README").write_text(
        "This dataset contains eye-tracking derivatives generated by "
        "Pyxations from the sibling raw BIDS dataset. Processed sample "
        "recordings use the physio suffix, and detected fixations, saccades, "
        "blinks, and retained messages use matching physioevents files. "
        "Human-readable plots may be generated under figures/; those report "
        "artifacts are not part of the standardized BIDS tables.\n",
        encoding="utf-8",
        newline="\n",
    )
    (derivative_root / ".bidsignore").write_text(
        "figures\nfigures/**\n",
        encoding="utf-8",
        newline="\n",
    )
    return derivative_root


class BIDSDerivativeExport:
    """Write and read a :class:`SessionTables` BIDS derivative session."""

    @staticmethod
    def _roots(session_path: Path) -> tuple[Path, Path]:
        derivative_root = session_path.parents[1]
        suffix = "_derivatives"
        raw_name = derivative_root.name.removesuffix(suffix)
        return derivative_root, derivative_root.with_name(raw_name)

    @staticmethod
    def _raw_sidecars(session_path: Path) -> list[tuple[Path, dict]]:
        _, raw_root = BIDSDerivativeExport._roots(session_path)
        folder = raw_root / session_path.parent.name / session_path.name / "beh"
        values = []
        for path in sorted(folder.glob("*_physio.json")):
            try:
                values.append((path, json.loads(path.read_text(encoding="utf-8"))))
            except (OSError, json.JSONDecodeError):
                continue
        return values

    @staticmethod
    def _source_prefix(session_path: Path, sidecars) -> str:
        if sidecars:
            stem = sidecars[0][0].name.removesuffix("_physio.json")
            return re.sub(r"_recording-[A-Za-z0-9]+$", "", stem)
        return f"{session_path.parent.name}_{session_path.name}_task-eyetracking"

    @staticmethod
    def _sample_columns(
        frame: pl.DataFrame,
    ) -> tuple[str, str, str | None, str]:
        columns = set(frame.columns)
        if {"X", "Y"}.issubset(columns):
            eye_values = (
                frame.get_column("eye")
                .drop_nulls()
                .cast(pl.String)
                .str.to_uppercase()
                .unique(maintain_order=True)
                .to_list()
                if "eye" in columns
                else []
            )
            recorded_eye = (
                "left"
                if eye_values == ["L"]
                else "right"
                if eye_values == ["R"]
                else "cyclopean"
            )
            return (
                "X",
                "Y",
                "Pupil" if "Pupil" in columns else None,
                recorded_eye,
            )
        candidates = [
            (
                "Gaze2d_Left.x",
                "Gaze2d_Left.y",
                "PupilDiam_Left",
                "left",
            ),
            ("LX", "LY", "LPupil", "left"),
            (
                "Gaze2d_Right.x",
                "Gaze2d_Right.y",
                "PupilDiam_Right",
                "right",
            ),
            ("RX", "RY", "RPupil", "right"),
        ]
        for x_column, y_column, pupil_column, eye in candidates:
            if {x_column, y_column}.issubset(columns):
                return (
                    x_column,
                    y_column,
                    pupil_column if pupil_column in columns else None,
                    eye,
                )
        raise ValueError(
            "Processed samples do not contain a supported gaze-coordinate pair"
        )

    @staticmethod
    def _time_column(frame: pl.DataFrame) -> str:
        for column in ("t_acum", "tSample", "timestamp"):
            if column in frame.columns:
                return column
        raise ValueError("Processed samples do not contain a timestamp column")

    @staticmethod
    def _source_metadata(sidecars, recorded_eye: str) -> dict:
        for _, metadata in sidecars:
            if metadata.get("RecordedEye") == recorded_eye:
                return metadata
        return sidecars[0][1] if sidecars else {}

    @staticmethod
    def _time_scale(frame: pl.DataFrame, time_column: str, metadata: dict) -> float:
        if time_column == "t_acum":
            return 1_000.0
        if {"TIMETICK", "BPOGX"}.intersection(frame.columns):
            return 1.0
        if {"Recording timestamp", "Gaze2d_Left.x"}.intersection(frame.columns):
            return 1_000_000.0
        return _unit_scale(metadata.get("timestamp", {}).get("Units"))

    @staticmethod
    def _read_auxiliary_json(session_path: Path, filename: str):
        path = session_path / filename
        if not path.is_file():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        finally:
            path.unlink(missing_ok=True)

    def write_session(
        self,
        session_path: str | Path,
        tables: SessionTables,
        *,
        detection_algorithm: str,
    ) -> tuple[Path, Path | None]:
        """Write one processed sample stream and its event annotations.

        Parameters
        ----------
        session_path : str or pathlib.Path
            Derivative session directory.
        tables : SessionTables
            Processed samples, events, behavior, and metadata to persist.
        detection_algorithm : str
            Detector label incorporated into the BIDS recording entity.

        Returns
        -------
        tuple of pathlib.Path and pathlib.Path or None
            Sample path and optional physiological-event path.

        Raises
        ------
        ValueError
            If samples lack required coordinates or valid timestamps.
        """

        session_path = Path(session_path)
        sample_frame = tables.samples
        sidecars = self._raw_sidecars(session_path)
        prefix = self._source_prefix(session_path, sidecars)
        label = bids_label(detection_algorithm.lower(), fallback="pyxations")
        base = f"{prefix}_recording-eye1{label}"
        destination = session_path / "beh"

        x_column, y_column, pupil_column, recorded_eye = self._sample_columns(
            sample_frame
        )
        time_column = self._time_column(sample_frame)
        source_metadata = self._source_metadata(sidecars, recorded_eye)
        time_scale = self._time_scale(sample_frame, time_column, source_metadata)
        raw_time = _numeric_series(sample_frame, time_column)
        finite_time = _finite_values(raw_time)
        if finite_time.is_empty():
            raise ValueError("Processed samples contain no valid timestamps")
        time_origin = float(finite_time[0])

        canonical_columns = {
            "timestamp": time_column,
            "x_coordinate": x_column,
            "y_coordinate": y_column,
        }
        if pupil_column:
            canonical_columns["pupil_size"] = pupil_column
        auxiliary_columns = [
            column
            for column in sample_frame.columns
            if column not in canonical_columns.values()
        ]
        original_to_bids, bids_to_original = _column_mapping(auxiliary_columns)
        expressions = [
            (
                (pl.col(time_column).cast(pl.Float64, strict=False) - time_origin)
                / time_scale
            ).alias("timestamp"),
            pl.col(x_column).cast(pl.Float64, strict=False).alias("x_coordinate"),
            pl.col(y_column).cast(pl.Float64, strict=False).alias("y_coordinate"),
        ]
        if pupil_column:
            expressions.append(
                pl.col(pupil_column).cast(pl.Float64, strict=False).alias("pupil_size")
            )
        expressions.extend(
            pl.col(original).alias(bids_column)
            for original, bids_column in original_to_bids.items()
        )
        standardized = (
            sample_frame.select(expressions)
            .filter(pl.col("timestamp").is_not_null() & pl.col("timestamp").is_finite())
            .sort("timestamp", maintain_order=True)
        )

        sampling_frequency = source_metadata.get("SamplingFrequency")
        if sampling_frequency is None and "Rate_recorded" in sample_frame.columns:
            rates = _finite_values(_numeric_series(sample_frame, "Rate_recorded"))
            sampling_frequency = float(rates.median()) if not rates.is_empty() else None
        sampling_frequency = float(
            sampling_frequency or _infer_frequency(standardized.get_column("timestamp"))
        )

        coordinate = source_metadata.get("x_coordinate", {})
        coordinate_unit = coordinate.get("Units", "arbitrary")
        coordinate_system = source_metadata.get("SampleCoordinateSystem", "custom")
        coordinate_description = source_metadata.get(
            "SampleCoordinateSystemDescription",
            "Coordinate system retained from the processed source recording.",
        )
        metadata = {
            "SamplingFrequency": sampling_frequency,
            "StartTime": 0.0,
            "Columns": standardized.columns,
            "PhysioType": "eyetrack",
            "RecordedEye": recorded_eye,
            "SampleCoordinateSystem": coordinate_system,
            "SampleCoordinateSystemDescription": coordinate_description,
            "Description": (
                "Eye-tracking samples processed by Pyxations using "
                f"{detection_algorithm}."
            ),
            "timestamp": {
                "Description": "Time elapsed since the first processed sample.",
                "Units": "s",
                "Origin": "First sample in the source recording",
            },
            "x_coordinate": {
                "Description": "Processed horizontal gaze coordinate.",
                "Units": coordinate_unit,
            },
            "y_coordinate": {
                "Description": "Processed vertical gaze coordinate.",
                "Units": coordinate_unit,
            },
            "PyxationsColumnMap": bids_to_original,
            "PyxationsCanonicalColumnMap": canonical_columns,
            "PyxationsSampleColumns": sample_frame.columns,
            "PyxationsSampleSchema": {
                column: str(dtype) for column, dtype in sample_frame.schema.items()
            },
            "PyxationsTimeOrigin": time_origin,
            "PyxationsTimeScale": time_scale,
            "PyxationsDetectionAlgorithm": detection_algorithm,
            "PyxationsCalibration": frame_payload(tables.calibration),
            "PyxationsHeader": frame_payload(tables.header),
            "PyxationsPreprocessingRecipe": self._read_auxiliary_json(
                session_path, "preprocessing_recipe.json"
            ),
            "PyxationsPreprocessingProvenance": self._read_auxiliary_json(
                session_path, "preprocessing_provenance.json"
            ),
            "PyxationsBehavioralEvents": frame_payload(tables.behavioral_events),
        }
        if "pupil_size" in standardized.columns:
            pupil_metadata = source_metadata.get("pupil_size", {})
            metadata["pupil_size"] = {
                "Description": pupil_metadata.get(
                    "Description",
                    "Processed pupil diameter or area as reported by the "
                    "source tracker; consult the source metadata for type.",
                ),
                "Units": pupil_metadata.get("Units", "arbitrary"),
            }
        for bids_column, original in bids_to_original.items():
            metadata[bids_column] = {
                "Description": (
                    f"Pyxations analysis column; original name: {original}."
                )
            }

        physio_path = destination / f"{base}_physio.tsv.gz"
        _write_json(destination / f"{base}_physio.json", metadata)
        write_tsv(
            physio_path,
            standardized,
            include_header=False,
            compressed=True,
        )

        event_path, _ = self._write_events(
            destination=destination,
            base=base,
            tables={
                "fix": tables.fixations,
                "sacc": tables.saccades,
                "blink": tables.blinks,
                "msg": tables.messages,
            },
            sample_time_origin=time_origin,
            sample_time_scale=time_scale,
            sample_duration=float(standardized.get_column("timestamp").max()),
        )
        return physio_path, event_path

    @staticmethod
    def _event_scale(
        onset: pl.Series,
        *,
        sample_time_origin: float,
        sample_time_scale: float,
        sample_duration: float,
        table_name: str,
    ) -> float:
        if table_name == "msg":
            return sample_time_scale
        candidates = []
        numeric = onset.cast(pl.Float64, strict=False)
        for scale in dict.fromkeys((sample_time_scale, 1_000.0, 1.0)):
            seconds = (numeric - sample_time_origin) / scale
            valid = _finite_values(seconds)
            score = (
                float(
                    (
                        (valid >= -1.0) & (valid <= max(sample_duration + 1.0, 1.0))
                    ).mean()
                )
                if not valid.is_empty()
                else 0.0
            )
            candidates.append((score, scale))
        return max(candidates, key=lambda item: item[0])[1]

    def _write_events(
        self,
        *,
        destination: Path,
        base: str,
        tables: Mapping[str, pl.DataFrame],
        sample_time_origin: float,
        sample_time_scale: float,
        sample_duration: float,
    ) -> tuple[Path | None, Path | None]:
        all_columns = [column for frame in tables.values() for column in frame.columns]
        original_to_bids, bids_to_original = _column_mapping(dict.fromkeys(all_columns))
        table_columns = {name: frame.columns for name, frame in tables.items()}
        event_names = {
            "fix": "fixation",
            "sacc": "saccade",
            "blink": "blink",
            "msg": "message",
        }

        prepared = []
        for table_name, original_frame in tables.items():
            if original_frame.is_empty():
                continue
            frame = original_frame
            onset_column = next(
                (
                    column
                    for column in ("tStart", "timestamp", "tSample", "tEnd")
                    if column in frame.columns
                ),
                None,
            )
            if onset_column is None:
                continue
            scale = self._event_scale(
                frame.get_column(onset_column),
                sample_time_origin=sample_time_origin,
                sample_time_scale=sample_time_scale,
                sample_duration=sample_duration,
                table_name=table_name,
            )
            onset = (
                (
                    pl.col(onset_column).cast(pl.Float64, strict=False)
                    - sample_time_origin
                )
                / scale
            ).alias("onset")
            if "duration" in frame.columns:
                duration = (
                    pl.col("duration").cast(pl.Float64, strict=False).fill_null(0.0)
                    / scale
                ).clip(lower_bound=0.0)
            elif "tEnd" in frame.columns and onset_column != "tEnd":
                duration = (
                    (
                        (
                            pl.col("tEnd").cast(pl.Float64, strict=False)
                            - pl.col(onset_column).cast(pl.Float64, strict=False)
                        )
                        / scale
                    )
                    .fill_null(0.0)
                    .clip(lower_bound=0.0)
                )
            else:
                duration = pl.lit(0.0)

            prepared.append(
                frame.select(
                    onset,
                    duration.alias("duration"),
                    pl.lit(event_names[table_name]).alias("trial_type"),
                    pl.lit(table_name).alias("pyxations_table"),
                    *[
                        pl.col(original).alias(original_to_bids[original])
                        for original in frame.columns
                    ],
                )
            )

        if not prepared:
            return None, None
        events = (
            pl.concat(prepared, how="diagonal_relaxed")
            .filter(pl.col("onset").is_not_null())
            .sort("onset", maintain_order=True)
        )
        if events.is_empty():
            return None, None

        metadata = {
            "Columns": events.columns,
            "Description": (
                "Fixations, saccades, blinks, and messages identified or "
                "retained by the Pyxations processing pipeline."
            ),
            "OnsetSource": "timestamp",
            "onset": {
                "Description": (
                    "Onset in seconds on the timeline of the associated "
                    "processed eye-tracking recording."
                ),
                "Units": "s",
            },
            "duration": {
                "Description": "Event duration.",
                "Units": "s",
            },
            "trial_type": {
                "Description": "Type of eye-movement or message event.",
                "Levels": {
                    "fixation": "Fixation event.",
                    "saccade": "Saccade event.",
                    "blink": "Blink event.",
                    "message": "Message retained from the source recording.",
                },
            },
            "pyxations_table": {
                "Description": (
                    "Original Pyxations table used to reconstruct the "
                    "analysis DataFrame."
                )
            },
            "PyxationsColumnMap": bids_to_original,
            "PyxationsTableColumns": table_columns,
        }
        for bids_column, original in bids_to_original.items():
            metadata[bids_column] = {
                "Description": (f"Pyxations event column; original name: {original}.")
            }

        event_path = destination / f"{base}_physioevents.tsv.gz"
        event_json = destination / f"{base}_physioevents.json"
        write_tsv(
            event_path,
            events,
            include_header=False,
            compressed=True,
        )
        _write_json(event_json, metadata)
        return event_path, event_json

    @staticmethod
    def _read_table(path: Path, metadata: Mapping) -> pl.DataFrame:
        return read_tsv(
            path,
            columns=list(metadata["Columns"]),
            has_header=False,
        )

    def read_session(
        self, session_path: str | Path, detection_algorithm: str
    ) -> SessionTables:
        """Load BIDS derivatives into the canonical session table model.

        Parameters
        ----------
        session_path : str or pathlib.Path
            Derivative session directory containing ``beh``.
        detection_algorithm : str
            Detector label used when the derivative files were written.

        Returns
        -------
        SessionTables
            Reconstructed samples, events, behavior, and metadata.

        Raises
        ------
        FileNotFoundError
            If no matching derivative physiological recording exists.
        """

        session_path = Path(session_path)
        label = bids_label(detection_algorithm.lower(), fallback="pyxations")
        physio_files = sorted(
            (session_path / "beh").glob(f"*_recording-eye1{label}_physio.tsv.gz")
        )
        if not physio_files:
            raise FileNotFoundError(
                f"No BIDS derivatives for {detection_algorithm} in {session_path}"
            )
        physio_path = physio_files[0]
        physio_metadata = json.loads(
            physio_path.with_suffix("").with_suffix(".json").read_text(encoding="utf-8")
        )
        samples_bids = self._read_table(physio_path, physio_metadata)
        sample_mapping = physio_metadata.get("PyxationsColumnMap", {})
        auxiliary_columns = [
            column for column in sample_mapping if column in samples_bids.columns
        ]
        canonical_mapping = physio_metadata.get("PyxationsCanonicalColumnMap", {})
        sample_schema = physio_metadata.get("PyxationsSampleSchema", {})
        time_origin = float(physio_metadata.get("PyxationsTimeOrigin", 0.0))
        time_scale = float(physio_metadata.get("PyxationsTimeScale", 1.0))

        sample_expressions = []
        for bids_column, original in canonical_mapping.items():
            if bids_column not in samples_bids.columns:
                continue
            expression = pl.col(bids_column)
            if bids_column == "timestamp":
                expression = expression * time_scale + time_origin
                if str(sample_schema.get(original, "")).startswith(("Int", "UInt")):
                    expression = expression.round()
            dtype = getattr(pl, str(sample_schema.get(original, "")), None)
            if dtype is not None:
                expression = expression.cast(dtype, strict=False)
            sample_expressions.append(expression.alias(original))
        sample_expressions.extend(
            pl.col(column).alias(sample_mapping[column]) for column in auxiliary_columns
        )
        samples = samples_bids.select(sample_expressions)
        sample_columns = list(
            physio_metadata.get("PyxationsSampleColumns", samples.columns)
        )
        missing = [column for column in sample_columns if column not in samples.columns]
        if missing:
            samples = samples.with_columns(
                pl.lit(None).alias(column) for column in missing
            )
        samples = samples.select(sample_columns)

        output = {
            "fix": pl.DataFrame(),
            "sacc": pl.DataFrame(),
            "blink": pl.DataFrame(),
            "msg": pl.DataFrame(),
        }
        event_path = physio_path.with_name(
            physio_path.name.replace("_physio.tsv.gz", "_physioevents.tsv.gz")
        )
        if event_path.is_file():
            event_metadata = json.loads(
                event_path.with_suffix("")
                .with_suffix(".json")
                .read_text(encoding="utf-8")
            )
            events = self._read_table(event_path, event_metadata)
            event_mapping = event_metadata.get("PyxationsColumnMap", {})
            table_columns = event_metadata.get("PyxationsTableColumns", {})
            for table_name in output:
                original_columns = list(table_columns.get(table_name, []))
                rows = events.filter(pl.col("pyxations_table") == table_name)
                bids_columns = [
                    bids_column
                    for bids_column, original in event_mapping.items()
                    if original in original_columns and bids_column in rows.columns
                ]
                if rows.is_empty():
                    output[table_name] = pl.DataFrame(
                        {column: [] for column in original_columns}
                    )
                    continue
                reconstructed = rows.select(bids_columns).rename(
                    {column: event_mapping[column] for column in bids_columns}
                )
                missing = [
                    column
                    for column in original_columns
                    if column not in reconstructed.columns
                ]
                if missing:
                    reconstructed = reconstructed.with_columns(
                        pl.lit(None).alias(column) for column in missing
                    )
                output[table_name] = reconstructed.select(original_columns)

        return SessionTables(
            samples=samples,
            fixations=output["fix"],
            saccades=output["sacc"],
            blinks=output["blink"],
            messages=output["msg"],
            calibration=payload_frame(physio_metadata.get("PyxationsCalibration")),
            header=payload_frame(physio_metadata.get("PyxationsHeader")),
            behavioral_events=payload_frame(
                physio_metadata.get("PyxationsBehavioralEvents")
            ),
            sampling_frequency=float(physio_metadata["SamplingFrequency"]),
        )
